INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (1, 'A1', 'A',2.4, 100, 0.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (2, 'A2', 'A',2.4, 100, 0.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (3, 'A3', 'A',2.4, 100, 0.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (4, 'A4', 'A',2.4, 100, 0.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (5, 'A5', 'A',2.4, 100, 0.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (6, 'A6', 'A',2.4, 100, 0.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (7, 'B1', 'B',3.2, 300, 0.5,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (8, 'B2', 'B',3.2, 300, 0.5,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (9, 'B3', 'B',3.2, 300, 0.5,'T');

