INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (12, 'A1', 'A',2.4, 100, 00.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (22, 'A2', 'A',2.4, 100, 00.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (33, 'A3', 'A',2.4, 100, 00.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (44, 'A4', 'A',2.4, 100, 00.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (55, 'A5', 'A',2.4, 100, 00.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (66, 'A6', 'A',2.4, 100, 00.3,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (77, 'B1', 'B',3.2, 300, 00.5,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (88, 'B2', 'B',3.2, 300, 00.5,'T');
INSERT INTO PARKING_LOTS (ID, LOT_NAME, FLOOR, LOT_HEIGHT, LOT_WEIGHT, LOT_PRICE, IS_EMPTY) VALUES (99, 'B3', 'B',3.2, 300, 00.5,'T');

